---
- name: Uninstall httpd server
  hosts: all
  tasks:
   - name: Stop and disable httpd service
     ansible.builtin.service:
      name: httpd
      state: stopped
      enabled: false
      
   - name: Remove httpd package
     ansible.builtin.package:
      name: httpd
      state: absent
